import PageHeader from './component/Header.jsx';
import CategoryMenu from './component/Categorymenu.jsx';
import { homeCategories } from './data/homecategories.js';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



function Home() {
  return (

    <div>
      
      <PageHeader />
      <CategoryMenu categories={homeCategories}/>

      <main>
      </main>
    </div>
  )
}
export default Home