import Header from './component/Header.jsx';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
function Home() {
  return (

    <div>
      <Header />
      <main>
      </main>
    </div>
  )
}
export default Home